# THIS FILE IS GENERATED BY author_tools/make_jitapi_wrappers.pl
# DO NOT EDIT

package LibJIT::PerlAPI;

our @AutoFunctions = qw(
    pa_get_pad_sv
    pa_sv_nv
    pa_sv_iv
    pa_sv_uv
    pa_sv_2mortal
    pa_new_sv_nv
    pa_new_sv_iv
    pa_new_sv_uv
    pa_get_targ
    pa_sv_true
    pa_sv_set_iv
    pa_sv_set_nv
    pa_push_sv
    pa_call_runloop
    pa_pop_sv
    pa_get_op_next
    pa_trap
);

1;
