# THIS FILE IS GENERATED BY author_tools/make_jitapi_wrappers.pl
# DO NOT EDIT

package LibJIT::PerlAPI;

our @AutoFunctions = qw(
    pa_get_pad_sv
    pa_get_pad_sv_address
    pa_sv_yes
    pa_sv_no
    pa_save_clearsv
    pa_pp_enterloop
    pa_pp_leaveloop
    pa_async_check
    pa_taint_not
    pa_freetmps
    pa_leave_scope
    pa_gv_sv
    pa_gv_svn
    pa_gv_av
    pa_gv_avn
    pa_gv_hv
    pa_sv_any
    pa_sv_flags
    pa_sv_nvx
    pa_sv_2nv_flags
    pa_sv_2nv
    pa_sv_nok_nog
    pa_sv_nv
    pa_sv_iv
    pa_sv_uv
    pa_sv_2mortal
    pa_new_sv_nv
    pa_new_sv_iv
    pa_new_sv_uv
    pa_new_mortal_sv
    pa_get_targ
    pa_av_fetch
    pa_av_fetch_lvalue
    pa_sv_true
    pa_sv_set_iv
    pa_sv_set_nv
    pa_sv_set_sv_nosteal
    pa_push_sv
    pa_call_runloop
    pa_pop_sv
    pa_get_op_next
    pa_trap
);

1;
