/* THIS FILE IS GENERATED BY author_tools/make_jitapi_wrappers.pl */
/* DO NOT EDIT */

#ifndef _LIBJIT_PERLAPI_H
#define _LIBJIT_PERLAPI_H

#include <jit/jit.h>

#ifdef PERL_IMPLICIT_CONTEXT
#define jit_tTHX  jit_type_void_ptr
#define jit_aTHX  thx
#else
#define jit_tTHX
#define jit_aTHX
#endif

jit_value_t pa_get_pad_sv(jit_function_t function, jit_value_t thx, jit_value_t padix);
jit_value_t pa_sv_2nv(jit_function_t function, jit_value_t thx, jit_value_t sv);
jit_value_t pa_get_targ(jit_function_t function, jit_value_t thx);
jit_value_t pa_sv_set_iv(jit_function_t function, jit_value_t thx, jit_value_t sv, jit_value_t iv);
jit_value_t pa_sv_set_nv(jit_function_t function, jit_value_t thx, jit_value_t sv, jit_value_t nv);
jit_value_t pa_push_sv(jit_function_t function, jit_value_t thx, jit_value_t sv);
jit_value_t pa_get_op_next(jit_function_t function, jit_value_t thx);
jit_value_t pa_trap(jit_function_t function, jit_value_t thx);

#endif // _LIBJIT_PERLAPI_H
